<tr height=15>
  <td><img src="images/menutop.gif" width="100" height="15" alt="" border="0" hspace="0" vspace="0"></td>
</tr>
<tr height=30>
  <td class="menuitem" id="menu0" onmouseout="SetActiveMenu( nosubmenu )" onmouseover="SetActiveMenu( submenu0 )">Cenník</td>
  <td>
  <div id="submenu0" class="offsubmenu" onmouseout="SetActiveMenu( nosubmenu )" onmouseover="SetActiveMenu( submenu0 )">
    <table width=100 cellspacing=0 cellpadding=0 class="submenu" style="position:absolute; top:142px;">
  	  <tr height=15>
	    <td><img src="images/menutop.gif" width="100" height="15" alt="" border="0" hspace="0" vspace="0"></td>
      </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu11">PcPrompt</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu12">Compaq</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu13">HP</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu14">Minolta</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu15">Epson</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu16">Komponenty</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu17">Monitory</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu18">Písacie stroje</td>
	  </tr>
	  <tr height=15>
	    <td><img src="images/menubottom.gif" width="100" height="15" alt="" border="0" hspace="0" vspace="0"></td>
      </tr>
    </table>
  </div>
  </td> 
</tr>
<tr height=30>
  <td class="menuitem" id="menu1">Zmluvy</td>
</tr>
<tr height=30>
  <td class="menuitem" id="menu2">Reklamácie</td>
</tr>
<tr height=30>
  <td class="menuitem" id="menu3" onmouseout="SetActiveMenu( nosubmenu )" onmouseover="SetActiveMenu( submenu3 )">Kontakt</td>
  <td>
  <div id="submenu3" class="offsubmenu" onmouseout="SetActiveMenu( nosubmenu )" onmouseover="SetActiveMenu( submenu3 )">
    <table width=100 cellspacing=0 cellpadding=0 class="submenu" style="position:absolute; top:232px;">
  	  <tr height=15>
	    <td><img src="images/menutop.gif" width="100" height="15" alt="" border="0" hspace="0" vspace="0"></td>
      </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu31">Bratislava</td>
	  </tr>
	  <tr height=15>
  	    <td class="menuitem" id="submenu32">Trenèín</td>
	  </tr>	  
	  <tr height=15>
	    <td><img src="images/menubottom.gif" width="100" height="15" alt="" border="0" hspace="0" vspace="0"></td>
      </tr>
    </table>
  </div>
  </td>
</tr>
<tr height=30 bgcolor=#eb4040>
  <td></td>
</tr>
<tr height=30 bgcolor=#eb4040>
  <td></td>
</tr>
<tr height=30 bgcolor=#eb4040>
  <td></td>
</tr>
<tr height=30 bgcolor=#eb4040>
  <td></td>
</tr>
<tr height=10 bgcolor=#eb4040>
  <td style="color=#ffffff"><center><small><small>17.10.2001</small></small></center></td>
</tr>
<tr>
  <td height=15><img src="images/menubottom.gif" width="100" height="15" alt="" border="0"></td>
</tr>

<div id="nosubmenu" class="offsubmenu">
</div>