<?
?>

<tr height=15 width=100>
  <td><img src="images/menutopr.gif" width="100" height="15" alt="" border="0"></td>
</tr>
<tr height=15 width=100 bgcolor=#eb4040>
  <td><center><input type=text size=8></center></td>
</tr>
<tr height=15 width=100 bgcolor=#eb4040>
  <td class="menuitem" id="menuhladaj">H¾adaj!</td>
</tr>
<tr height=27 width=100 bgcolor=#eb4040>
  <td></td>
</tr>
<tr height=15 width=100>
  <td><img src="images/menubottomr.gif" width="100" height="15" alt="" border="0"></td>
</tr>