vti_encoding:SR|utf8-nl
vti_author:SR|Rado
vti_modifiedby:SR|Rado
vti_timecreated:TR|13 Mar 2000 15:40:32 -0000
vti_timelastmodified:TR|13 Mar 2000 15:40:32 -0000
vti_backlinkinfo:VX|my/zoznam.html fotky/fotky.html onas/zoznam.html onas/onas.html my/my.html
vti_extenderversion:SR|4.0.2.2717
vti_syncwith_www.geocities.com\:80/septimagjh:TR|13 Mar 2000 15:40:32 -0000
vti_syncofs_ftp.nasatrieda.miesto.sk\:21:TW|06 May 1999 14:56:00 -0000
vti_syncwith_ftp.nasatrieda.miesto.sk\:21:TR|13 Mar 2000 14:40:34 -0000
